# Generated by Django 6.0.1 on 2026-01-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zeptoDB',
            fields=[
                ('Address', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=10)),
                ('offers', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100)),
                ('feedback', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
